"""
URL configuration for financial management API.

This module defines all API endpoints for the financial management system,
including RESTful routes for resources and custom action endpoints.
"""

import logging

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

# Get structured logger for this module
logger = logging.getLogger(__name__)

# Initialize DefaultRouter for RESTful API endpoints
router = DefaultRouter()
workspace_router = DefaultRouter()

# User settings endpoints are now handled by a custom URL pattern

# Expense categories endpoints (read-only)
router.register(
    r"expense-categories", views.ExpenseCategoryViewSet, basename="expensecategory"
)

# Income categories endpoints (read-only)
router.register(
    r"income-categories", views.IncomeCategoryViewSet, basename="incomecategory"
)

# Exchange rates endpoints (read-only)
router.register(r"exchange-rates", views.ExchangeRateViewSet, basename="exchange-rate")

# Workspace management endpoints (registered with both routers for different path prefixes)
workspace_router.register(r"", views.WorkspaceViewSet, basename="workspace")

# Debugging statement to inspect URLs generated by workspace_router
for p in workspace_router.urls:
    logger.debug(f"Workspace Router URL: {p}")

# Workspace admin management endpoints
router.register(
    r"workspace-admins", views.WorkspaceAdminViewSet, basename="workspaceadmin"
)


# Custom API endpoints for bulk operations and synchronization
urlpatterns = [
    # Include all router-generated URLs
    path("", include(router.urls)),
    # --- SINGLETON USER SETTINGS ENDPOINT ---
    path("user-settings/", views.UserSettingsViewSet.as_view({"get": "retrieve", "patch": "partial_update"}), name="user-settings-detail"),
]

# Export workspace specific URLs for direct inclusion at /api/workspaces/
workspace_urlpatterns = [
    path("", include(workspace_router.urls)),

    # --- NESTED TRANSACTION ENDPOINTS ---
    path(
        "workspaces/<int:workspace_pk>/transactions/",
        views.TransactionViewSet.as_view({"get": "list", "post": "create"}),
        name="workspace-transaction-list",
    ),
    path(
        "workspaces/<int:workspace_pk>/transactions/<int:pk>/",
        views.TransactionViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="workspace-transaction-detail",
    ),
    # --- NESTED TAGS ENDPOINTS ---
    path(
        "workspaces/<int:workspace_pk>/tags/",
        views.TagViewSet.as_view({"get": "list", "post": "create"}),
        name="workspace-tag-list",
    ),
    path(
        "workspaces/<int:workspace_pk>/tags/<int:pk>/",
        views.TagViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="workspace-tag-detail",
    ),
    # --- NESTED TRANSACTION DRAFTS ENDPOINTS ---
    path(
        "workspaces/<int:workspace_pk>/transaction-drafts/",
        views.TransactionDraftViewSet.as_view({"get": "list", "post": "create"}),
        name="workspace-transactiondraft-list",
    ),
    path(
        "workspaces/<int:workspace_pk>/transaction-drafts/<int:pk>/",
        views.TransactionDraftViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="workspace-transactiondraft-detail",
    ),
    # --- NESTED CATEGORY SYNC ENDPOINTS ---
    path(
        "workspaces/<int:workspace_pk>/categories/<str:category_type>/sync/",
        views.CategorySyncViewSet.as_view({"post": "sync_categories"}),
        name="workspace-category-sync",
    ),
    # DEPRECATED - will be removed after frontend update
    path(
        "workspaces/<int:workspace_id>/categories/<str:category_type>/sync/",
        views.CategorySyncViewSet.as_view({"post": "sync_categories"}),
        name="category-sync-sync-categories",  # Keeping old name for backward compatibility
    ),
    # Workspace members endpoint
    path(
        "workspaces/<int:pk>/members/",
        views.WorkspaceViewSet.as_view(
            {
                "get": "members",
                "patch": "members",  # Update member role
                "delete": "members",  # Remove member
            }
        ),
        name="workspace-members",
    ),
    # Workspace hard delete endpoint (PRIBUDOL - existuje v views)
    path(
        "workspaces/<int:pk>/hard-delete/",
        views.WorkspaceViewSet.as_view({"delete": "hard_delete"}),
        name="workspace-hard-delete",
    ),
    # Workspace activate endpoint (PRIBUDOL - existuje v views)
    path(
        "workspaces/<int:pk>/activate/",
        views.WorkspaceViewSet.as_view({"post": "activate"}),
        name="workspace-activate",
    ),
    # Workspace membership info endpoint (PRIBUDOL - existuje v views)
    path(
        "workspaces/<int:pk>/membership-info/",
        views.WorkspaceViewSet.as_view({"get": "membership_info"}),
        name="workspace-membership-info",
    ),
    # Bulk transaction synchronization endpoint
    # --- NESTED WORKSPACE SETTINGS ENDPOINT ---
    path(
        "workspaces/<int:workspace_pk>/settings/",
        views.WorkspaceSettingsViewSet.as_view(
            {"get": "retrieve", "put": "update", "patch": "partial_update"}
        ),
        name="workspace-settings-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/transactions/bulk-sync/",
        views.TransactionViewSet.as_view({"post": "bulk_sync"}),
        name="bulk-sync-transactions",
    ),
    # Transaction draft save endpoint (PRIBUDOL - existuje v views)
    # This is now handled by the POST to /workspaces/<workspace_pk>/transaction-drafts/
    # path(
    #     "workspaces/<int:workspace_pk>/transaction-drafts/save-draft/",
    #     views.TransactionDraftViewSet.as_view({"post": "save_draft"}),
    #     name="transaction-draft-save",
    # ),
    # Transaction draft get workspace draft endpoint (PRIBUDOL - existuje v views)
    path(
        "workspaces/<int:workspace_pk>/transaction-drafts/get-workspace-draft/",
        views.TransactionDraftViewSet.as_view({"get": "get_workspace_draft"}),
        name="transaction-draft-get-workspace",
    ),
    # Discard is now handled by DELETE on /workspaces/<workspace_pk>/transaction-drafts/<pk>/
    # Category usage endpoints
    path(
        "expense-categories/<int:pk>/usage/",
        views.ExpenseCategoryViewSet.as_view({"get": "usage"}),
        name="expense-category-usage",
    ),
    path(
        "income-categories/<int:pk>/usage/",
        views.IncomeCategoryViewSet.as_view({"get": "usage"}),
        name="income-category-usage",
    ),
    # Workspace admin management
    path(
        "workspaces/<int:workspace_pk>/assign-admin/",
        views.WorkspaceAdminViewSet.as_view({"post": "assign_admin"}),
        name="workspaceadmin-assign-admin",
    ),
    path(
        "workspace-admins/<int:pk>/deactivate/",
        views.WorkspaceAdminViewSet.as_view({"post": "deactivate_admin"}),
        name="workspace-deactivate-admin",
    ),
    # Workspace member management
    path(
        "workspaces/<int:pk>/change-owner/",
        views.WorkspaceViewSet.as_view({"post": "change_owner"}),
        name="workspace-change-owner",
    ),
]

# Log URL configuration on startup
custom_endpoints_count = len(urlpatterns) - 1  # Subtract the include route
logger.info(
    "Financial API URLs configured successfully",
    extra={
        "total_routes": len(router.urls) + custom_endpoints_count,
        "viewset_endpoints": len(router.registry),
        "custom_endpoints": custom_endpoints_count,
        "action": "url_configuration_loaded",
        "component": "urls",
    },
)

# Log detailed route information in debug mode
logger.debug(
    "Detailed route configuration",
    extra={
        "registered_viewsets": [
            {
                "prefix": route[0],
                "viewset": route[1].__class__.__name__,
                "basename": route[2],
            }
            for route in router.registry
        ],
        "custom_routes": [
            {
                "pattern": (
                    pattern.pattern._route
                    if hasattr(pattern.pattern, "_route")
                    else str(pattern.pattern)
                ),
                "name": getattr(pattern, "name", "unnamed"),
            }
            for pattern in urlpatterns
            if hasattr(pattern, "pattern")
        ],
        "action": "route_detailed_log",
        "component": "urls",
    },
)
