# Generated by Django 5.2.7 on 2025-10-31 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("rate_to_eur", models.DecimalField(decimal_places=6, max_digits=20)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Exchange rates",
                "ordering": ["-date"],
                "unique_together": {("currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Level 1 - Root"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5 - Leaf"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="finance.expensecategory"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense categories",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategoryProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[("cost", "Only cost"), ("expense", "Only expense")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="finance.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense category properties",
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategoryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense category versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="finance.expensecategoryversion",
            ),
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Level 1 - Root"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                            (5, "Level 5 - Leaf"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True, related_name="parents", to="finance.incomecategory"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Income categories",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncomeCategoryProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Only revenue"),
                            ("income", "Only income"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="finance.incomecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Income category properties",
            },
        ),
        migrations.CreateModel(
            name="IncomeCategoryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Income category versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="finance.incomecategoryversion",
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("cs", "Czech"), ("sk", "Slovak")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incomecategoryversion",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.workspace"
            ),
        ),
        migrations.AddField(
            model_name="expensecategoryversion",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.workspace"
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workspace memberships",
                "unique_together": {("workspace", "user")},
            },
        ),
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="workspaces",
                through="finance.WorkspaceMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domestic_currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                            ("GBP", "British Pound"),
                            ("CHF", "Swiss Franc"),
                            ("PLN", "Polish Zloty"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[("month", "Month only"), ("day", "Full date")],
                        default="month",
                        max_length=5,
                    ),
                ),
                ("accounting_mode", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="finance.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transactions_data", models.JSONField(default=list)),
                (
                    "draft_type",
                    models.CharField(
                        blank=True,
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transaction drafts",
                "ordering": ["-last_modified"],
                "indexes": [
                    models.Index(
                        fields=["user", "workspace", "draft_type"],
                        name="finance_tra_user_id_db1ca3_idx",
                    ),
                    models.Index(
                        fields=["last_modified"], name="finance_tra_last_mo_bec3e6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "workspace", "draft_type"),
                        name="unique_draft_per_workspace_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("original_currency", models.CharField(max_length=3)),
                (
                    "amount_domestic",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("date", models.DateField()),
                ("month", models.DateField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("note_manual", models.TextField(blank=True)),
                ("note_auto", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_transactions",
                        to="finance.expensecategory",
                    ),
                ),
                (
                    "income_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_transactions",
                        to="finance.incomecategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="finance_tra_user_id_3294c0_idx"
                    ),
                    models.Index(
                        fields=["user", "month"], name="finance_tra_user_id_be7a6c_idx"
                    ),
                    models.Index(
                        fields=["user", "type"], name="finance_tra_user_id_35643f_idx"
                    ),
                    models.Index(
                        fields=["workspace", "date"],
                        name="finance_tra_workspa_1e5b85_idx",
                    ),
                ],
            },
        ),
    ]
