# Generated by Django 5.2.7 on 2025-11-07 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_impersonate", models.BooleanField(default=True)),
                ("can_manage_users", models.BooleanField(default=True)),
                ("can_manage_categories", models.BooleanField(default=True)),
                ("can_manage_settings", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Workspace admins",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="usersettings",
            options={"verbose_name_plural": "User settings"},
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expensecategoryversion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomecategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomecategoryversion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["owner", "is_active"], name="finance_wor_owner_i_42a053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["is_active"], name="finance_wor_is_acti_2b720c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["created_at"], name="finance_wor_created_abd4c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["user", "role"], name="finance_wor_user_id_c79875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["workspace", "role"], name="finance_wor_workspa_291cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["joined_at"], name="finance_wor_joined__1901a6_idx"
            ),
        ),
        migrations.AddField(
            model_name="workspaceadmin",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_workspace_admins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceadmin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_admin_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceadmin",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_assignments",
                to="finance.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceadmin",
            index=models.Index(
                fields=["user", "is_active"], name="finance_wor_user_id_ca2ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceadmin",
            index=models.Index(
                fields=["workspace", "is_active"], name="finance_wor_workspa_c1e3f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceadmin",
            index=models.Index(
                fields=["assigned_at"], name="finance_wor_assigne_bef654_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceadmin",
            unique_together={("user", "workspace")},
        ),
    ]
