# Generated by Django 5.2.7 on 2025-11-08 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_workspaceadmin_alter_usersettings_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("cz", "Czech"), ("sk", "Slovak")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["workspace", "month"], name="idx_workspace_month"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["workspace", "type", "date"], name="idx_workspace_type_date"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["workspace", "user"], name="idx_workspace_user"),
        ),
    ]
