# Generated by Django 5.2.7 on 2025-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_usersettings_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceadmin",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[("editor", "Editor"), ("viewer", "Viewer")],
                default="viewer",
                max_length=10,
            ),
        ),
    ]
