# Generated by Django 5.2.7 on 2025-11-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_workspaceadmin_deactivated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceadmin",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deactivated_workspace_admins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("workspace",),
                name="unique_owner_per_workspace",
            ),
        ),
    ]
