# Generated by Django 5.2.7 on 2025-11-23 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_expensecategoryversion_levels_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("DD.MM.YYYY", "DD.MM.YYYY"),
                    ("MM/DD/YYYY", "MM/DD/YYYY"),
                    ("YYYY-MM-DD", "YYYY-MM-DD"),
                ],
                default="DD.MM.YYYY",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("GBP", "British Pound"),
                    ("CHF", "Swiss Franc"),
                    ("PLN", "Polish Zloty"),
                    ("CZK", "Czech Koruna"),
                ],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="expensecategoryversion",
            name="levels_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="incomecategoryversion",
            name="levels_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
