# Generated by Django 5.2.7 on 2025-11-07 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_social_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="User's unique email address, required for all accounts",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts. New users are inactive until email verification.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_social_account",
            field=models.BooleanField(
                default=False,
                help_text="True if this account was created via Google registration",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Optional password, can be null for Google registration",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_completed",
            field=models.BooleanField(
                default=False,
                help_text="True if password and username/nickname have been set",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture (JPG, JPEG, PNG formats supported)",
                null=True,
                upload_to="profile_pics/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional username, can be null for Google registration",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
